In [108]:
import pandas as pd, ast

In [109]:
df = pd.read_csv('WorkoutProducts.csv')

df['category'].value_counts()

category
упоры для отжиманий            1500
фитнес резинки                 1500
брусья                         1500
гимнастические кольца          1500
турник                         1200
пояс с цепью для отягощения    1100
Name: count, dtype: int64

In [110]:
df.columns

Index(['Unnamed: 0', 'id', '__sort', 'ksort', 'root', 'kindId', 'brand',
       'brandId', 'siteBrandId', 'colors', 'subjectId', 'subjectParentId',
       'semanticId', 'name', 'entity', 'matchId', 'supplier', 'supplierId',
       'supplierRating', 'supplierFlags', 'pics', 'rating', 'reviewRating',
       'nmReviewRating', 'feedbacks', 'nmFeedbacks', 'panelPromoId', 'volume',
       'weight', 'viewFlags', 'sizes', 'totalQuantity', 'time1', 'time2', 'wh',
       'dtype', 'dist', 'meta', 'category', 'feedbackPoints', 'mtype',
       'isNew'],
      dtype='object')

In [111]:
df = df[['id', 'name', 'brand', 'category', 'rating', 'feedbacks', 'supplierRating', 'sizes']]
df.iloc[0]['sizes']

"[{'name': '', 'origName': '0', 'rank': 0, 'optionId': 1210745356, 'wh': 117986, 'time1': 2, 'time2': 42, 'dtype': 6597069766664, 'price': {'basic': 156700, 'product': 99500, 'logistics': 0, 'return': 0, 'cashback': 0}, 'saleConditions': 134217728, 'payload': 'A3UtfCms/Tw3ERRG8Po6MhE7B+Y0pXyKJ+XOTK70NtoMnprXPQZ02Ed9DA1cu2DTJS7XRP4a1VEMsZDhu0IeW3NMYjQOQaMNB+DGmyUPfj1/gS8JOKoUBmcsU5Z9AVu4xEGrOP6xvwJSyprpmuakJNHBa0AeY5ObUzqP7EYEwN/2OzldZv18PJLFT7nk66kXBCc8L4/1sfckrYZAvulP0i7mA7xyZ14+50QDmEr2j/TxMm9R3lEjZDjkG9P6mjdDfC4i6VQe5CnAg7fHtitVLYa11hXvByXVmtpYbmyLnw'}]"

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8300 entries, 0 to 8299
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              8300 non-null   int64
 1   name            8300 non-null   object
 2   brand           6832 non-null   object
 3   category        8300 non-null   object
 4   rating          8300 non-null   int64
 5   feedbacks       8300 non-null   int64
 6   supplierRating  8300 non-null   float64
 7   sizes           8300 non-null   object
dtypes: float64(1), int64(3), object(4)
memory usage: 518.9+ KB

In [113]:
df['sizes'] = df['sizes'].apply(lambda x: ast.literal_eval(x))

type(df.iloc[0]['sizes'])

list

In [114]:
df['base_price'] = df['sizes'].apply(lambda x: x[0]['price']['basic']/100.0)
df['discount_price'] = df['sizes'].apply(lambda x: x[0]['price']['product']/100.0)

In [115]:
df.head()

,id,name,brand,category,rating,feedbacks,supplierRating,sizes,base_price,discount_price
0,809284740,Турник настенный 3в1 спортивный для дома,Sportlex,турник,4,5,4.7,"[{'name': '', 'origName': '0', 'rank': 0, 'opt...",1567.0,995.0
1,809248305,Турник настенный 3в1 спортивный для дома,Sportlex,турник,5,1,4.7,"[{'name': '', 'origName': '0', 'rank': 0, 'opt...",2293.0,1290.0
2,567252697,Турник настенный 3 в 1,ЭРГОЛАЙН,турник,5,1809,4.8,"[{'name': '', 'origName': '0', 'rank': 0, 'opt...",8800.0,3474.0
3,617571040,Турник настенный 2 хвата,TURNIK.COM,турник,5,639,4.9,"[{'name': '', 'origName': '0', 'rank': 0, 'opt...",12294.0,1448.0
4,172172838,Турник распорный раздвижной в дверной проем,Velton,турник,5,5376,4.8,"[{'name': '', 'origName': '0', 'rank': 0, 'opt...",1267.0,448.0

In [116]:
df = df.drop(columns='sizes')

In [117]:
df

,id,name,brand,category,rating,feedbacks,supplierRating,base_price,discount_price
0,809284740,Турник настенный 3в1 спортивный для дома,Sportlex,турник,4,5,4.7,1567.0,995.0
1,809248305,Турник настенный 3в1 спортивный для дома,Sportlex,турник,5,1,4.7,2293.0,1290.0
2,567252697,Турник настенный 3 в 1,ЭРГОЛАЙН,турник,5,1809,4.8,8800.0,3474.0
3,617571040,Турник настенный 2 хвата,TURNIK.COM,турник,5,639,4.9,12294.0,1448.0
4,172172838,Турник распорный раздвижной в дверной проем,Velton,турник,5,5376,4.8,1267.0,448.0
...,...,...,...,...,...,...,...,...,...
8295,533630185,Гимнастические кольца деревянные 18 см,NaN,гимнастические кольца,5,41,4.9,2100.0,981.0
8296,28698075,Кольца к Уличному спортивному комплексу,Sportlim,гимнастические кольца,5,42,4.8,1311.0,735.0
8297,806277280,"Гимнастические кольца, диаметр хвата 11 мм",NaN,гимнастические кольца,0,0,4.4,3523.0,690.0
8298,175982156,Кольца гимнастические 28 мм (без строп),Мир спорта 365,гимнастические кольца,5,19,4.9,4000.0,1495.0
8299,37317741,"Стропы для гимнастических колец, 37 мм",Мир спорта 365,гимнастические кольца,5,40,4.9,3400.0,1270.0

In [118]:
df.to_csv('Cleaned_Workout_Products.csv')